import { CalculationResult, ComparisonItem } from '../types';

/**
 * Exports calculation steps as a CSV file download
 */
export function downloadCSV(result: CalculationResult) {
  const headers = ['Step', 'From Cylinder', 'To Cylinder', 'Seek Distance', 'Direction', 'Cumulative Movement', 'Step Type', 'Notes'];
  const rows = result.steps.map(s => [
    s.step,
    s.from,
    s.to,
    s.seekDistance,
    s.direction,
    s.cumulativeMovement,
    s.type.toUpperCase(),
    `"${(s.note || '').replace(/"/g, '""')}"`
  ]);

  // Summary lines
  const csvContent = [
    `# Disk Scheduling Algorithm Calculation: ${result.algorithm}`,
    `# Initial Head: ${result.initialHead}, Disk Size: ${result.diskSize}, Direction: ${result.direction || 'N/A'}`,
    `# Request Queue: ${result.requestQueue.join(' ')}`,
    `# Total Head Movement: ${result.totalHeadMovement} cylinders, Average Seek Distance: ${result.averageSeekDistance} cylinders`,
    '',
    headers.join(','),
    ...rows.map(r => r.join(','))
  ].join('\n');

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `disk-scheduling-${result.algorithm.toLowerCase()}-${Date.now()}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Copies a markdown / plain text summary of the calculation to clipboard
 */
export async function copySummaryToClipboard(result: CalculationResult): Promise<boolean> {
  const summary = [
    `========================================`,
    `DISK SCHEDULING CALCULATION: ${result.algorithm}`,
    `========================================`,
    `Initial Head Position : ${result.initialHead}`,
    `Disk Cylinder Range    : 0 to ${result.diskSize - 1} (Size: ${result.diskSize})`,
    `Direction              : ${result.direction || 'Not applicable'}`,
    `Requests (${result.requestCount})        : [${result.requestQueue.join(', ')}]`,
    `----------------------------------------`,
    `Service Sequence       : ${result.serviceOrder.join(' -> ')}`,
    `Total Head Movement    : ${result.totalHeadMovement} cylinders`,
    `Average Seek Distance  : ${result.averageSeekDistance} cylinders/request`,
    `----------------------------------------`,
    `Steps Breakdown:`,
    ...result.steps.map(s => `  Step ${s.step}: ${s.from} -> ${s.to} | Seek: ${s.seekDistance} | Dir: ${s.direction} | Cumul: ${s.cumulativeMovement} (${s.type})`),
    `========================================`,
    `Generated by Disk Scheduling Algorithm Calculator`,
  ].join('\n');

  try {
    await navigator.clipboard.writeText(summary);
    return true;
  } catch {
    return false;
  }
}

/**
 * Formats a shareable comparison summary text
 */
export async function copyComparisonToClipboard(items: ComparisonItem[], initialHead: number, queue: number[]): Promise<boolean> {
  const text = [
    `========================================`,
    `DISK SCHEDULING ALGORITHM COMPARISON`,
    `========================================`,
    `Initial Head : ${initialHead}`,
    `Queue        : [${queue.join(', ')}]`,
    `----------------------------------------`,
    `Algorithm | Total Movement | Avg Seek | Service Sequence`,
    ...items.map(item => `${item.algorithm.padEnd(8)} | ${String(item.totalMovement).padStart(14)} | ${String(item.averageSeek).padStart(8)} | ${item.serviceOrder.join(' -> ')}`),
    `========================================`,
  ].join('\n');

  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}
